// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReply struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type MailCodeSendReply struct {
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}
