// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReply struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
